// lib/components/ability-cards.tsx
import * as AbilityService from "../domains/abilities";
import { Ability } from "../types";

export function AbilityView(data: Ability[]) {
  return (
    <div className="dnd-ui-ability-scores-container">
      <div className="dnd-ui-ability-scores-grid">
        {data.map((item) => (
          <div className={`dnd-ui-ability-score-card ${item.isProficient ? "dnd-ui-proficient" : ""}`} key={item.label}>
            <div className="dnd-ui-ability-header">
              <p className="dnd-ui-ability-name">{item.label}</p>
              <p className="dnd-ui-ability-value">{item.total}</p>
            </div>
            <p className="dnd-ui-ability-modifier">{AbilityService.formatModifier(item.modifier)}</p>

            <div className="dnd-ui-ability-modifier-saving">
              <em>Saving {AbilityService.formatModifier(item.savingThrow)}</em>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// lib/components/AbilityCards.vue
<script setup lang="ts">
interface AbilityCardItem {
  label: string;
  total: number;
  modifier: string;
  isProficient: boolean;
  savingThrow: string;
}

defineProps<{
  abilities: AbilityCardItem[];
}>();
</script>

<template>
  <div class="dnd-ui-ability-scores-container">
    <div class="dnd-ui-ability-scores-grid">
      <div
        v-for="item in abilities"
        :key="item.label"
        :class="['dnd-ui-ability-score-card', { 'dnd-ui-proficient': item.isProficient }]"
      >
        <div class="dnd-ui-ability-header">
          <p class="dnd-ui-ability-name">{{ item.label }}</p>
          <p class="dnd-ui-ability-value">{{ item.total }}</p>
        </div>
        <p class="dnd-ui-ability-modifier">{{ item.modifier }}</p>
        <div class="dnd-ui-ability-modifier-saving">
          <em>Saving {{ item.savingThrow }}</em>
        </div>
      </div>
    </div>
  </div>
</template>
