// lib/components/Checkbox.vue
<script setup lang="ts">
const props = defineProps<{
  id: string;
  checked: boolean;
  className?: string;
}>();

const emit = defineEmits<{
  toggle: [];
}>();
</script>

<template>
  <button
    :id="props.id"
    :class="['dnd-ui-checkbox-button', 'clickable-icon', props.className ?? '']"
    :aria-pressed="props.checked"
    type="button"
    @click="emit('toggle')"
  />
</template>

// lib/components/checkbox.tsx
export type CheckboxProps = {
  id: string;
  checked: boolean;
  onChange: () => void;
  className?: string;
};

export function Checkbox({ id, checked, onChange, className }: CheckboxProps) {
  return (
    <button
      id={id}
      className={`dnd-ui-checkbox-button clickable-icon ${className || ""}`}
      onClick={onChange}
      aria-pressed={checked}
      type="button"
    />
  );
}
