// lib/components/ConsumableCheckboxes.vue
<script setup lang="ts">
import type { ParsedConsumableBlock } from "lib/types";
import type { ConsumableState } from "lib/domains/consumables";
import Checkbox from "lib/components/Checkbox.vue";

const props = defineProps<{
  static: ParsedConsumableBlock;
  state: ConsumableState;
}>();

const emit = defineEmits<{
  "update:state": [newState: ConsumableState];
}>();

function toggleUsage(index: number) {
  let newValue: number;

  if (index < props.state.value) {
    newValue = index;
  } else {
    newValue = index + 1;
  }

  emit("update:state", { value: newValue });
}
</script>

<template>
  <div class="dnd-ui-consumable-container">
    <span v-if="props.static.label" class="dnd-ui-consumable-label">{{ props.static.label }}</span>
    <div class="dnd-ui-consumable-boxes">
      <Checkbox
        v-for="i in props.static.uses"
        :key="i - 1"
        :checked="i - 1 < props.state.value"
        :id="`consumable-${props.static.state_key}-${i - 1}`"
        @toggle="toggleUsage(i - 1)"
      />
    </div>
  </div>
</template>

// lib/components/consumable-checkboxes.tsx
import { ParsedConsumableBlock } from "lib/types";
import { ConsumableState } from "lib/domains/consumables";
import { Checkbox } from "lib/components/checkbox";

export type ConsumableCheckboxesProps = {
  static: ParsedConsumableBlock;
  state: ConsumableState;
  onStateChange: (newState: ConsumableState) => void;
};

export function ConsumableCheckboxes(props: ConsumableCheckboxesProps) {
  // Toggle usage of a specific checkbox
  const toggleUsage = (index: number) => {
    let newValue = props.state.value;

    // If the checkbox was checked (index < available uses)
    if (index < props.state.value) {
      // Uncheck this box
      newValue = index;
    } else {
      // Check this box
      newValue = index + 1;
    }

    props.onStateChange({
      value: newValue,
    });
  };

  // Render checkboxes for uses
  const renderCheckboxes = () => {
    const checkboxes = [];
    for (let i = 0; i < props.static.uses; i++) {
      checkboxes.push(
        <Checkbox
          key={i}
          checked={i < props.state.value}
          id={`consumable-${props.static.state_key}-${i}`}
          onChange={() => toggleUsage(i)}
        />
      );
    }
    return checkboxes;
  };

  return (
    <div className="dnd-ui-consumable-container">
      {props.static.label && <span className="dnd-ui-consumable-label">{props.static.label}</span>}
      <div className="dnd-ui-consumable-boxes">{renderCheckboxes()}</div>
    </div>
  );
}
