// lib/components/EventButtons.vue
<script setup lang="ts">
import type { EventButtonsBlock } from "lib/types";

const props = defineProps<{
  config: EventButtonsBlock;
}>();

const emit = defineEmits<{
  click: [value: string | { event: string; amount: number }];
}>();
</script>

<template>
  <div class="dnd-ui-event-buttons-container">
    <button
      v-for="(button, index) in props.config.items"
      :key="index"
      class="dnd-ui-event-button"
      :title="`Trigger ${button.name} event`"
      @click="emit('click', button.value)"
    >
      <span class="dnd-ui-event-button-text">{{ button.name }}</span>
    </button>
  </div>
</template>

// lib/components/event-buttons.tsx
import { EventButtonsBlock } from "lib/types";

export type EventButtonsProps = {
  config: EventButtonsBlock;
  onButtonClick: (value: string | { event: string; amount: number }) => void;
};

export function EventButtons(props: EventButtonsProps) {
  const handleClick = (value: string | { event: string; amount: number }) => {
    props.onButtonClick(value);
  };

  return (
    <div className="dnd-ui-event-buttons-container">
      {props.config.items.map((button, index) => (
        <button
          key={index}
          className="dnd-ui-event-button"
          onClick={() => handleClick(button.value)}
          title={`Trigger ${button.name} event`}
        >
          <span className="dnd-ui-event-button-text">{button.name}</span>
        </button>
      ))}
    </div>
  );
}
