// lib/components/HealthCard.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import type { ParsedHealthBlock } from "lib/types";
import { HealthState, isSingleHitDiceState, isMultiHitDiceState, hasSingleHitDice } from "lib/domains/healthpoints";
import Checkbox from "lib/components/Checkbox.vue";

const props = defineProps<{
  static: ParsedHealthBlock;
  state: HealthState;
}>();

const emit = defineEmits<{
  "update:state": [newState: HealthState];
}>();

const inputValue = ref("1");

const maxHealth = computed(() => (typeof props.static.health === "number" ? props.static.health : 6));

const healthPercentage = computed(() => Math.max(0, Math.min(100, (props.state.current / maxHealth.value) * 100)));

function handleHeal() {
  const value = parseInt(inputValue.value) || 0;
  if (value <= 0) return;

  const newCurrent = Math.min(props.state.current + value, maxHealth.value);
  const newState: HealthState = {
    ...props.state,
    current: newCurrent,
  };

  if (newCurrent > 0 && props.state.current <= 0) {
    newState.deathSaveSuccesses = 0;
    newState.deathSaveFailures = 0;
  }

  emit("update:state", newState);
  inputValue.value = "1";
}

function handleDamage() {
  const value = parseInt(inputValue.value) || 0;
  if (value <= 0) return;

  let newTemp = props.state.temporary;
  let newCurrent = props.state.current;

  if (newTemp > 0) {
    if (value <= newTemp) {
      newTemp -= value;
    } else {
      const remainingDamage = value - newTemp;
      newTemp = 0;
      newCurrent = Math.max(0, newCurrent - remainingDamage);
    }
  } else {
    newCurrent = Math.max(0, newCurrent - value);
  }

  emit("update:state", {
    ...props.state,
    current: newCurrent,
    temporary: newTemp,
  });
  inputValue.value = "1";
}

function handleTempHP() {
  const value = parseInt(inputValue.value) || 0;
  if (value <= 0) return;

  const newTemp = Math.max(props.state.temporary, value);

  emit("update:state", {
    ...props.state,
    temporary: newTemp,
  });
  inputValue.value = "1";
}

function calculateNewUsedCount(currentUsed: number, index: number): number {
  const isUsed = index < currentUsed;
  if (isUsed) {
    return index;
  } else {
    return index + 1;
  }
}

function toggleHitDie(diceType: string | null, index: number) {
  if (!diceType && isSingleHitDiceState(props.state)) {
    const newHitDiceUsed = calculateNewUsedCount(props.state.hitdiceUsed, index);
    emit("update:state", {
      ...props.state,
      hitdiceUsed: newHitDiceUsed,
    });
  } else if (diceType && isMultiHitDiceState(props.state)) {
    const currentUsed = props.state.hitdiceUsed[diceType] || 0;
    const newUsed = calculateNewUsedCount(currentUsed, index);
    emit("update:state", {
      ...props.state,
      hitdiceUsed: {
        ...(props.state.hitdiceUsed as Record<string, number>),
        [diceType]: newUsed,
      },
    });
  }
}

function toggleDeathSave(type: "success" | "failure", index: number) {
  const newState = { ...props.state };

  if (type === "success") {
    const isChecked = index < props.state.deathSaveSuccesses;
    newState.deathSaveSuccesses = isChecked ? index : index + 1;
  } else {
    const isChecked = index < props.state.deathSaveFailures;
    newState.deathSaveFailures = isChecked ? index : index + 1;
  }

  emit("update:state", newState);
}

function getHitDiceUsed(hd: { dice: string; value: number }): number {
  if (hasSingleHitDice(props.static) && isSingleHitDiceState(props.state)) {
    return props.state.hitdiceUsed;
  } else if (isMultiHitDiceState(props.state)) {
    return props.state.hitdiceUsed[hd.dice] || 0;
  }
  return 0;
}
</script>

<template>
  <div class="dnd-ui-health-card dnd-ui-generic-card">
    <div class="dnd-ui-health-card-header">
      <div class="dnd-ui-generic-card-label">{{ props.static.label || "Hit Points" }}</div>
      <div class="dnd-ui-health-value">
        {{ props.state.current }}
        <span class="dnd-ui-health-max">/ {{ maxHealth }}</span>
        <span v-if="props.state.temporary > 0" class="dnd-ui-health-temp">+{{ props.state.temporary }} temp</span>
      </div>
    </div>

    <div class="dnd-ui-health-progress-container">
      <div class="dnd-ui-health-progress-bar" :style="{ width: `${healthPercentage}%` }" />
    </div>

    <div class="dnd-ui-health-controls">
      <input
        type="number"
        class="dnd-ui-health-input"
        :value="inputValue"
        placeholder="0"
        aria-label="Health points"
        @input="inputValue = ($event.target as HTMLInputElement).value"
      />
      <button type="button" class="dnd-ui-health-button dnd-ui-health-heal" @click="handleHeal">Heal</button>
      <button type="button" class="dnd-ui-health-button dnd-ui-health-damage" @click="handleDamage">Damage</button>
      <button type="button" class="dnd-ui-health-button dnd-ui-health-temp" @click="handleTempHP">Temp HP</button>
    </div>

    <template v-if="props.static.hitdice && props.static.hitdice.length > 0">
      <div class="dnd-ui-health-divider" />
      <div class="dnd-ui-hit-dice-container">
        <div class="dnd-ui-hit-dice-list">
          <div v-for="hd in props.static.hitdice" :key="hd.dice" class="dnd-ui-hit-dice-row">
            <p class="dnd-ui-hit-dice-label">HIT DICE ({{ hd.dice }})</p>
            <div class="dnd-ui-hit-dice-boxes">
              <Checkbox
                v-for="i in hd.value"
                :key="`${hd.dice}-${i - 1}`"
                :checked="i - 1 < getHitDiceUsed(hd)"
                :id="`hit-dice-${hd.dice}-${i - 1}`"
                @toggle="toggleHitDie(hasSingleHitDice(props.static) ? null : hd.dice, i - 1)"
              />
            </div>
          </div>
        </div>
      </div>
    </template>

    <template v-if="props.static.death_saves && props.state.current <= 0">
      <div class="dnd-ui-health-divider" />
      <div class="dnd-ui-death-saves-container">
        <div class="dnd-ui-death-saves-tracker">
          <div class="dnd-ui-death-saves-failures">
            <Checkbox
              v-for="i in 3"
              :key="`failure-${i - 1}`"
              :checked="i - 1 < props.state.deathSaveFailures"
              :id="`death-save-failure-${i - 1}`"
              class-name="dnd-ui-death-save-failure"
              @toggle="toggleDeathSave('failure', i - 1)"
            />
          </div>
          <div class="dnd-ui-death-saves-skull">&#x1F480;</div>
          <div class="dnd-ui-death-saves-successes">
            <Checkbox
              v-for="i in 3"
              :key="`success-${i - 1}`"
              :checked="i - 1 < props.state.deathSaveSuccesses"
              :id="`death-save-success-${i - 1}`"
              class-name="dnd-ui-death-save-success"
              @toggle="toggleDeathSave('success', i - 1)"
            />
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

// lib/components/health-card.tsx
import { useState } from "react";
import type { ParsedHealthBlock } from "lib/types";
import { HealthState, isSingleHitDiceState, isMultiHitDiceState, hasSingleHitDice } from "lib/domains/healthpoints";
import { Checkbox } from "lib/components/checkbox";

export type HealthCardProps = {
  static: ParsedHealthBlock;
  state: HealthState;
  onStateChange: (newState: HealthState) => void;
};

export function HealthCard(props: HealthCardProps) {
  const [inputValue, setInputValue] = useState("1");

  // Ensure health is a number for calculations
  const maxHealth = typeof props.static.health === "number" ? props.static.health : 6;

  // Calculate health percentage for progress bar
  const healthPercentage = Math.max(0, Math.min(100, (props.state.current / maxHealth) * 100));

  // Event handlers for health actions
  const handleHeal = () => {
    const value = parseInt(inputValue) || 0;
    if (value <= 0) return;

    const newCurrent = Math.min(props.state.current + value, maxHealth);
    const newState = {
      ...props.state,
      current: newCurrent,
    };

    // Reset death saves if health goes above 0
    if (newCurrent > 0 && props.state.current <= 0) {
      newState.deathSaveSuccesses = 0;
      newState.deathSaveFailures = 0;
    }

    props.onStateChange(newState);
    setInputValue("1");
  };

  const handleDamage = () => {
    const value = parseInt(inputValue) || 0;
    if (value <= 0) return;

    let newTemp = props.state.temporary;
    let newCurrent = props.state.current;

    // Apply damage to temporary HP first
    if (newTemp > 0) {
      if (value <= newTemp) {
        newTemp -= value;
      } else {
        const remainingDamage = value - newTemp;
        newTemp = 0;
        newCurrent = Math.max(0, newCurrent - remainingDamage);
      }
    } else {
      newCurrent = Math.max(0, newCurrent - value);
    }

    props.onStateChange({
      ...props.state,
      current: newCurrent,
      temporary: newTemp,
    });
    setInputValue("1");
  };

  const handleTempHP = () => {
    const value = parseInt(inputValue) || 0;
    if (value <= 0) return;

    // Only replace temporary HP if the new value is higher
    const newTemp = Math.max(props.state.temporary, value);

    props.onStateChange({
      ...props.state,
      temporary: newTemp,
    });
    setInputValue("1");
  };

  // Helper function to calculate new used count based on toggle action
  const calculateNewUsedCount = (currentUsed: number, index: number): number => {
    const isUsed = index < currentUsed;
    if (isUsed) {
      // Uncheck this die and all dice after it
      return index;
    } else {
      // Check this die and all dice before it
      return index + 1;
    }
  };

  // Handle hit dice interaction
  const toggleHitDie = (diceType: string | null, index: number) => {
    if (!diceType && isSingleHitDiceState(props.state)) {
      // Legacy single dice type
      const newHitDiceUsed = calculateNewUsedCount(props.state.hitdiceUsed, index);

      props.onStateChange({
        ...props.state,
        hitdiceUsed: newHitDiceUsed,
      });
    } else if (diceType && isMultiHitDiceState(props.state)) {
      // Multiple dice types
      const currentUsed = props.state.hitdiceUsed[diceType] || 0;
      const newUsed = calculateNewUsedCount(currentUsed, index);

      props.onStateChange({
        ...props.state,
        hitdiceUsed: {
          ...(props.state.hitdiceUsed as Record<string, number>),
          [diceType]: newUsed,
        },
      });
    }
  };

  // Handle death save interaction
  const toggleDeathSave = (type: "success" | "failure", index: number) => {
    const newState = { ...props.state };

    if (type === "success") {
      const isChecked = index < props.state.deathSaveSuccesses;
      if (isChecked) {
        newState.deathSaveSuccesses = index;
      } else {
        newState.deathSaveSuccesses = index + 1;
      }
    } else {
      const isChecked = index < props.state.deathSaveFailures;
      if (isChecked) {
        newState.deathSaveFailures = index;
      } else {
        newState.deathSaveFailures = index + 1;
      }
    }

    props.onStateChange(newState);
  };

  // Handle hit dice rendering
  const renderHitDice = () => {
    if (!props.static.hitdice || props.static.hitdice.length === 0) return null;

    return (
      <div className="dnd-ui-hit-dice-list">
        {props.static.hitdice.map((hd) => {
          // Get the used count based on state structure
          let used: number = 0;

          if (hasSingleHitDice(props.static) && isSingleHitDiceState(props.state)) {
            // Legacy single dice with number state
            used = props.state.hitdiceUsed;
          } else if (isMultiHitDiceState(props.state)) {
            // Multiple dice or migrated state
            used = props.state.hitdiceUsed[hd.dice] || 0;
          }

          const hitDiceArray = [];
          for (let i = 0; i < hd.value; i++) {
            hitDiceArray.push(
              <Checkbox
                key={`${hd.dice}-${i}`}
                checked={i < used}
                id={`hit-dice-${hd.dice}-${i}`}
                onChange={() => toggleHitDie(hasSingleHitDice(props.static) ? null : hd.dice, i)}
              />
            );
          }

          return (
            <div key={hd.dice} className="dnd-ui-hit-dice-row">
              <p className="dnd-ui-hit-dice-label">HIT DICE ({hd.dice})</p>
              <div className="dnd-ui-hit-dice-boxes">{hitDiceArray}</div>
            </div>
          );
        })}
      </div>
    );
  };

  // Handle death saves rendering
  const renderDeathSaves = () => {
    if (!props.static.death_saves || props.state.current > 0) return null;

    const failures = [];
    const successes = [];

    // Render failures (left side)
    for (let i = 0; i < 3; i++) {
      failures.push(
        <Checkbox
          key={`failure-${i}`}
          checked={i < props.state.deathSaveFailures}
          id={`death-save-failure-${i}`}
          onChange={() => toggleDeathSave("failure", i)}
          className="dnd-ui-death-save-failure"
        />
      );
    }

    // Render successes (right side)
    for (let i = 0; i < 3; i++) {
      successes.push(
        <Checkbox
          key={`success-${i}`}
          checked={i < props.state.deathSaveSuccesses}
          id={`death-save-success-${i}`}
          onChange={() => toggleDeathSave("success", i)}
          className="dnd-ui-death-save-success"
        />
      );
    }

    return { failures, successes };
  };

  return (
    <div className="dnd-ui-health-card dnd-ui-generic-card">
      <div className="dnd-ui-health-card-header">
        <div className="dnd-ui-generic-card-label">{props.static.label || "Hit Points"}</div>
        <div className="dnd-ui-health-value">
          {props.state.current}
          <span className="dnd-ui-health-max">/ {maxHealth}</span>
          {props.state.temporary > 0 && <span className="dnd-ui-health-temp">+{props.state.temporary} temp</span>}
        </div>
      </div>

      <div className="dnd-ui-health-progress-container">
        <div className="dnd-ui-health-progress-bar" style={{ width: `${healthPercentage}%` }} />
      </div>

      <div className="dnd-ui-health-controls">
        <input
          type="number"
          className="dnd-ui-health-input"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder="0"
          aria-label="Health points"
        />
        <button type="button" className="dnd-ui-health-button dnd-ui-health-heal" onClick={handleHeal}>
          Heal
        </button>
        <button type="button" className="dnd-ui-health-button dnd-ui-health-damage" onClick={handleDamage}>
          Damage
        </button>
        <button type="button" className="dnd-ui-health-button dnd-ui-health-temp" onClick={handleTempHP}>
          Temp HP
        </button>
      </div>

      {props.static.hitdice && props.static.hitdice.length > 0 && (
        <>
          <div className="dnd-ui-health-divider" />
          <div className="dnd-ui-hit-dice-container">{renderHitDice()}</div>
        </>
      )}

      {props.static.death_saves && props.state.current <= 0 && (
        <>
          <div className="dnd-ui-health-divider" />
          <div className="dnd-ui-death-saves-container">
            <div className="dnd-ui-death-saves-tracker">
              <div className="dnd-ui-death-saves-failures">{renderDeathSaves()?.failures}</div>
              <div className="dnd-ui-death-saves-skull">💀</div>
              <div className="dnd-ui-death-saves-successes">{renderDeathSaves()?.successes}</div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
