// lib/components/Initiative.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import type {
  InitiativeBlock,
  InitiativeItem,
  InitiativeConsumable,
  ParsedConsumableBlock,
} from "lib/types";
import {
  getSortedInitiativeItems,
  getMaxHp,
  itemHashKey,
  InitiativeState,
} from "lib/domains/initiative";
import MultiConsumableCheckboxes from "lib/components/MultiConsumableCheckboxes.vue";
import type { ConsumableState } from "lib/domains/consumables";

const props = defineProps<{
  static: InitiativeBlock;
  state: InitiativeState;
}>();

const emit = defineEmits<{
  "update:state": [newState: InitiativeState];
}>();

const inputValue = ref("1");

const sortedItems = computed(() =>
  getSortedInitiativeItems(props.static.items, props.state.initiatives),
);

function adaptInitiativeConsumable(consumable: InitiativeConsumable): ParsedConsumableBlock {
  return {
    label: consumable.label,
    state_key: consumable.state_key,
    uses: consumable.uses,
    reset_on: consumable.reset_on_round ? [{ event: "round", amount: undefined }] : undefined,
  };
}

function handleSetInitiative(item: InitiativeItem, value: string) {
  const itemHash = itemHashKey(item);
  const initiativeValue = parseInt(value) || 0;
  const newInitiatives = { ...props.state.initiatives };

  newInitiatives[itemHash] = initiativeValue;
  emit("update:state", {
    ...props.state,
    initiatives: newInitiatives,
  });
}

function handleDamage(
  item: InitiativeItem,
  monsterKey: string,
  value: string,
  type: "damage" | "heal" = "damage",
) {
  const parsedValue = parseInt(value) || 0;
  if (parsedValue <= 0) return;

  const itemHash = itemHashKey(item);

  const newHp = { ...props.state.hp };
  if (!newHp[itemHash]) {
    newHp[itemHash] = {};
  }

  const currentHp = newHp[itemHash][monsterKey] || 0;

  let applyValue = 0;
  if (type === "damage") {
    applyValue = Math.max(0, currentHp - parsedValue);
  } else {
    const maxHp = getMaxHp(item, monsterKey);
    applyValue = Math.min(maxHp, currentHp + parsedValue);
  }

  newHp[itemHash] = {
    ...newHp[itemHash],
    [monsterKey]: applyValue,
  };

  emit("update:state", { ...props.state, hp: newHp });
}

function handleNext() {
  if (sortedItems.value.length === 0) return;

  const currentActiveIndex = props.state.activeIndex;
  let nextActiveIndex = -1;
  let newRound = props.state.round;
  const newConsumables = { ...(props.state.consumables || {}) };

  const currentActiveItemIndex = sortedItems.value.findIndex(
    (item) => item.index === currentActiveIndex,
  );

  if (currentActiveItemIndex === -1 || currentActiveItemIndex === sortedItems.value.length - 1) {
    nextActiveIndex = sortedItems.value[0].index;
    if (currentActiveItemIndex !== -1) {
      newRound = props.state.round + 1;

      if (props.static.consumables) {
        props.static.consumables.forEach((consumable) => {
          if (consumable.reset_on_round) {
            newConsumables[consumable.state_key] = 0;
          }
        });
      }
    }
  } else {
    nextActiveIndex = sortedItems.value[currentActiveItemIndex + 1].index;
  }

  emit("update:state", {
    ...props.state,
    activeIndex: nextActiveIndex,
    round: newRound,
    consumables: newConsumables,
  });
}

function handlePrev() {
  if (sortedItems.value.length === 0) return;

  const currentActiveIndex = props.state.activeIndex;
  let prevActiveIndex = -1;
  let newRound = props.state.round;

  const currentActiveItemIndex = sortedItems.value.findIndex(
    (item) => item.index === currentActiveIndex,
  );

  if (currentActiveItemIndex === -1 || currentActiveItemIndex === 0) {
    prevActiveIndex = sortedItems.value[sortedItems.value.length - 1].index;
    if (currentActiveItemIndex !== -1 && props.state.round > 1) {
      newRound = props.state.round - 1;
    }
  } else {
    prevActiveIndex = sortedItems.value[currentActiveItemIndex - 1].index;
  }

  emit("update:state", {
    ...props.state,
    activeIndex: prevActiveIndex,
    round: newRound,
  });
}

function handleReset() {
  const newInitiatives = { ...props.state.initiatives };
  const newHp: Record<string, Record<string, number>> = {};
  const newConsumables: Record<string, number> = {};

  props.static.items.forEach((item) => {
    const indexStr = itemHashKey(item);
    newInitiatives[indexStr] = 0;
    newHp[indexStr] = {};

    if (typeof item.hp === "number") {
      newHp[indexStr]["main"] = item.hp;
    } else if (item.hp && typeof item.hp === "object") {
      Object.entries(item.hp).forEach(([key, value]) => {
        newHp[indexStr][key] = value as number;
      });
    }
  });

  if (props.static.consumables) {
    props.static.consumables.forEach((consumable) => {
      newConsumables[consumable.state_key] = 0;
    });
  }

  emit("update:state", {
    ...props.state,
    activeIndex: -1,
    initiatives: newInitiatives,
    hp: newHp,
    round: 1,
    consumables: newConsumables,
  });
}

function handleConsumableStateChange(stateKey: string, newState: ConsumableState) {
  const newConsumables = { ...(props.state.consumables || {}) };
  newConsumables[stateKey] = newState.value;

  emit("update:state", {
    ...props.state,
    consumables: newConsumables,
  });
}

function getMonsterStatusClass(currentHp: number, maxHp: number): string {
  const healthPercent = maxHp > 0 ? (currentHp / maxHp) * 100 : 0;
  if (currentHp <= 0) return "dnd-ui-monster-status-dead";
  if (healthPercent <= 33) return "dnd-ui-monster-status-injured";
  if (healthPercent >= 90) return "dnd-ui-monster-status-healthy";
  return "";
}

function getSingleMonsterStatusClass(item: InitiativeItem): string {
  const hashKey = itemHashKey(item);
  const itemHp = props.state.hp[hashKey] || {};
  const monsterKey = Object.keys(itemHp)[0] || "main";
  const maxHp = getMaxHp(item);
  const currentHp = itemHp[monsterKey] || 0;
  const healthPercent = maxHp > 0 ? (currentHp / maxHp) * 100 : 0;
  if (currentHp <= 0) return "dnd-ui-monster-status-dead";
  if (healthPercent <= 33) return "dnd-ui-monster-status-injured";
  return "";
}

function consumableStates(): Record<string, ConsumableState> {
  if (!props.static.consumables) return {};
  return Object.fromEntries(
    props.static.consumables.map((consumable) => [
      consumable.state_key,
      { value: props.state.consumables?.[consumable.state_key] || 0 },
    ]),
  );
}
</script>

<template>
  <div class="dnd-ui-initiative-tracker">
    <div class="dnd-ui-initiative-tracker-controls">
      <div class="dnd-ui-initiative-round-counter">
        Round: <span class="dnd-ui-initiative-round-value">{{ props.state.round }}</span>
      </div>
      <button
        class="dnd-ui-initiative-control-button dnd-ui-initiative-prev"
        aria-label="Previous combatant"
        @click="handlePrev"
      >
        &#x25C0; Prev
      </button>
      <button
        class="dnd-ui-initiative-control-button dnd-ui-initiative-next"
        aria-label="Next combatant"
        @click="handleNext"
      >
        Next &#x25B6;
      </button>
      <button
        class="dnd-ui-initiative-control-button dnd-ui-initiative-reset"
        aria-label="Reset initiative"
        @click="handleReset"
      >
        Reset
      </button>
    </div>

    <!-- Consumables Section -->
    <MultiConsumableCheckboxes
      v-if="props.static.consumables && props.static.consumables.length > 0"
      :consumables="props.static.consumables.map(adaptInitiativeConsumable)"
      :states="consumableStates()"
      @update:state-change="handleConsumableStateChange"
    />

    <div class="dnd-ui-initiative-list">
      <div v-if="sortedItems.length === 0" class="dnd-ui-initiative-empty-state">
        No combatants added
      </div>
      <div v-else class="dnd-ui-initiative-items">
        <div
          v-for="{ item, index, initiative } in sortedItems"
          :key="index"
          :class="[
            'dnd-ui-initiative-item',
            index === props.state.activeIndex ? 'dnd-ui-initiative-item-active' : '',
            item.hp !== undefined &&
            typeof item.hp === 'object' &&
            Object.keys(item.hp).length > 1
              ? 'dnd-ui-initiative-item-group'
              : '',
          ]"
        >
          <div class="dnd-ui-initiative-item-main">
            <div class="dnd-ui-initiative-roll">
              <input
                type="number"
                :value="initiative || ''"
                class="dnd-ui-initiative-input"
                placeholder="0"
                @change="
                  handleSetInitiative(
                    props.static.items[index],
                    ($event.target as HTMLInputElement).value,
                  )
                "
              />
            </div>
            <div>
              <div class="dnd-ui-initiative-name">
                <a v-if="item.link" :href="item.link" class="dnd-ui-initiative-link">{{
                  item.name
                }}</a>
                <template v-else>{{ item.name }}</template>
              </div>
              <div class="dnd-ui-initiative-ac">
                AC: <span class="dnd-ui-initiative-ac-value">{{ item.ac }}</span>
              </div>
            </div>

            <!-- Single monster HP inline -->
            <template
              v-if="
                item.hp !== undefined &&
                !(typeof item.hp === 'object' && Object.keys(item.hp).length > 1)
              "
            >
              <div
                :class="[
                  'dnd-ui-initiative-hp-inline',
                  getSingleMonsterStatusClass(item),
                ]"
              >
                <div class="dnd-ui-initiative-hp-display">
                  <span class="dnd-ui-initiative-hp-value">{{
                    props.state.hp[itemHashKey(item)]?.[
                      Object.keys(props.state.hp[itemHashKey(item)] || {})[0] || 'main'
                    ] || 0
                  }}</span>
                  <span class="dnd-ui-initiative-hp-separator">/</span>
                  <span class="dnd-ui-initiative-hp-max">{{ getMaxHp(item) }}</span>
                </div>
                <div class="dnd-ui-initiative-hp-controls">
                  <input
                    type="number"
                    class="dnd-ui-initiative-hp-input"
                    placeholder="0"
                    :value="inputValue"
                    @input="inputValue = ($event.target as HTMLInputElement).value"
                  />
                  <button
                    class="dnd-ui-initiative-hp-button dnd-ui-initiative-damage"
                    title="Damage"
                    @click="
                      handleDamage(
                        props.static.items[index],
                        Object.keys(props.state.hp[itemHashKey(item)] || {})[0] || 'main',
                        inputValue,
                      );
                      inputValue = '1';
                    "
                  >
                    &#x2212;
                  </button>
                  <button
                    class="dnd-ui-initiative-hp-button dnd-ui-initiative-heal"
                    title="Heal"
                    @click="
                      handleDamage(
                        props.static.items[index],
                        Object.keys(props.state.hp[itemHashKey(item)] || {})[0] || 'main',
                        inputValue,
                        'heal',
                      );
                      inputValue = '1';
                    "
                  >
                    +
                  </button>
                </div>
              </div>
            </template>
          </div>

          <!-- Group monster HP -->
          <template
            v-if="
              item.hp !== undefined &&
              typeof item.hp === 'object' &&
              Object.keys(item.hp).length > 1
            "
          >
            <div class="dnd-ui-divider"></div>
            <div class="dnd-ui-initiative-group-container">
              <div class="dnd-ui-initiative-group-hp">
                <div
                  v-for="[key, maxHp] in Object.entries(item.hp as Record<string, number>)"
                  :key="`${index}-${key}`"
                  class="dnd-ui-initiative-monster"
                >
                  <div class="dnd-ui-initiative-monster-header">
                    <span
                      :class="[
                        'dnd-ui-initiative-monster-name',
                        getMonsterStatusClass(
                          props.state.hp[itemHashKey(item)]?.[key] || 0,
                          maxHp,
                        ),
                      ]"
                      >{{ key }}</span
                    >
                    <span class="dnd-ui-initiative-monster-hp">
                      <span class="dnd-ui-initiative-hp-value">{{
                        props.state.hp[itemHashKey(item)]?.[key] || 0
                      }}</span>
                      <span class="dnd-ui-initiative-hp-separator">/</span>
                      <span class="dnd-ui-initiative-hp-max">{{ maxHp }}</span>
                    </span>
                  </div>
                  <div class="dnd-ui-initiative-monster-actions">
                    <input
                      type="number"
                      class="dnd-ui-initiative-hp-input"
                      placeholder="0"
                      @input="inputValue = ($event.target as HTMLInputElement).value"
                    />
                    <button
                      class="dnd-ui-initiative-hp-button dnd-ui-initiative-damage"
                      title="Damage"
                      @click="
                        handleDamage(props.static.items[index], key, inputValue);
                        inputValue = '1';
                      "
                    >
                      &#x2212;
                    </button>
                    <button
                      class="dnd-ui-initiative-hp-button dnd-ui-initiative-heal"
                      title="Heal"
                      @click="
                        handleDamage(props.static.items[index], key, inputValue, 'heal');
                        inputValue = '1';
                      "
                    >
                      +
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>

// lib/components/initiative.tsx
import { useState } from "react";
import type { InitiativeBlock, InitiativeItem, InitiativeConsumable, ParsedConsumableBlock } from "lib/types";
import { getSortedInitiativeItems, getMaxHp, itemHashKey, InitiativeState } from "lib/domains/initiative";
import { MultiConsumableCheckboxes } from "lib/components/multi-consumable-checkboxes";
import { ConsumableState } from "lib/domains/consumables";

export type InitiativeProps = {
  static: InitiativeBlock;
  state: InitiativeState;
  onStateChange: (newState: InitiativeState) => void;
};

// Convert InitiativeConsumable to ParsedConsumableBlock format for ConsumableCheckboxes
function adaptInitiativeConsumable(consumable: InitiativeConsumable): ParsedConsumableBlock {
  return {
    label: consumable.label,
    state_key: consumable.state_key,
    uses: consumable.uses,
    reset_on: consumable.reset_on_round ? [{ event: "round", amount: undefined }] : undefined,
  };
}

export function Initiative(props: InitiativeProps) {
  const [inputValue, setInputValue] = useState<string>("1");

  const sortedItems = getSortedInitiativeItems(props.static.items, props.state.initiatives);

  const handleSetInitiative = (item: InitiativeItem, value: string) => {
    const itemHash = itemHashKey(item);
    const initiativeValue = parseInt(value) || 0;
    const newInitiatives = { ...props.state.initiatives };

    newInitiatives[itemHash] = initiativeValue;
    props.onStateChange({
      ...props.state,
      initiatives: newInitiatives,
    });
  };

  const handleDamage = (
    item: InitiativeItem,
    monsterKey: string,
    value: string,
    type: "damage" | "heal" = "damage"
  ) => {
    const parsedValue = parseInt(value) || 0;
    if (parsedValue <= 0) {
      return;
    }

    const itemHash = itemHashKey(item);

    const newHp = { ...props.state.hp };
    if (!newHp[itemHash]) {
      newHp[itemHash] = {};
    }

    const currentHp = newHp[itemHash][monsterKey] || 0;

    let applyValue = 0;
    if (type === "damage") {
      applyValue = Math.max(0, currentHp - parsedValue);
    } else {
      const maxHp = getMaxHp(item, monsterKey);
      applyValue = Math.min(maxHp, currentHp + parsedValue);
    }

    newHp[itemHash] = {
      ...newHp[itemHash],
      [monsterKey]: applyValue,
    };

    props.onStateChange({ ...props.state, hp: newHp });
  };

  const handleNext = () => {
    if (sortedItems.length === 0) return;

    const currentActiveIndex = props.state.activeIndex;
    let nextActiveIndex = -1;
    let newRound = props.state.round;
    const newConsumables = { ...(props.state.consumables || {}) };

    // Find the index of the current active item in the sorted list
    const currentActiveItemIndex = sortedItems.findIndex((item) => item.index === currentActiveIndex);

    if (currentActiveItemIndex === -1 || currentActiveItemIndex === sortedItems.length - 1) {
      // If no active item or at the end of the list, go to the first item
      nextActiveIndex = sortedItems[0].index;
      // Increment round when cycling back to the beginning
      if (currentActiveItemIndex !== -1) {
        newRound = props.state.round + 1;

        // Reset consumables that have reset_on_round: true
        if (props.static.consumables) {
          props.static.consumables.forEach((consumable) => {
            if (consumable.reset_on_round) {
              newConsumables[consumable.state_key] = 0;
            }
          });
        }
      }
    } else {
      // Otherwise, go to the next item
      nextActiveIndex = sortedItems[currentActiveItemIndex + 1].index;
    }

    props.onStateChange({
      ...props.state,
      activeIndex: nextActiveIndex,
      round: newRound,
      consumables: newConsumables,
    });
  };

  const handlePrev = () => {
    if (sortedItems.length === 0) return;

    const currentActiveIndex = props.state.activeIndex;
    let prevActiveIndex = -1;
    let newRound = props.state.round;

    // Find the index of the current active item in the sorted list
    const currentActiveItemIndex = sortedItems.findIndex((item) => item.index === currentActiveIndex);

    if (currentActiveItemIndex === -1 || currentActiveItemIndex === 0) {
      // If no active item or at the beginning of the list, go to the last item
      prevActiveIndex = sortedItems[sortedItems.length - 1].index;
      // Decrement round when cycling back to the end
      if (currentActiveItemIndex !== -1 && props.state.round > 1) {
        newRound = props.state.round - 1;
      }
    } else {
      // Otherwise, go to the previous item
      prevActiveIndex = sortedItems[currentActiveItemIndex - 1].index;
    }

    props.onStateChange({
      ...props.state,
      activeIndex: prevActiveIndex,
      round: newRound,
    });
  };

  const handleReset = () => {
    // Reset all initiatives to 0 and HP to max values
    const newInitiatives = { ...props.state.initiatives };
    const newHp: Record<string, Record<string, number>> = {};
    const newConsumables: Record<string, number> = {};

    props.static.items.forEach((item) => {
      const indexStr = itemHashKey(item);
      newInitiatives[indexStr] = 0;
      newHp[indexStr] = {};

      if (typeof item.hp === "number") {
        newHp[indexStr]["main"] = item.hp;
      } else if (item.hp && typeof item.hp === "object") {
        Object.entries(item.hp).forEach(([key, value]) => {
          newHp[indexStr][key] = value as number;
        });
      }
    });

    // Reset all consumables to 0
    if (props.static.consumables) {
      props.static.consumables.forEach((consumable) => {
        newConsumables[consumable.state_key] = 0;
      });
    }

    props.onStateChange({
      ...props.state,
      activeIndex: -1,
      initiatives: newInitiatives,
      hp: newHp,
      round: 1, // Reset to round 1
      consumables: newConsumables,
    });
  };

  // Handle consumable state change from MultiConsumableCheckboxes
  const handleConsumableStateChange = (stateKey: string, newState: ConsumableState) => {
    const newConsumables = { ...(props.state.consumables || {}) };
    newConsumables[stateKey] = newState.value;

    props.onStateChange({
      ...props.state,
      consumables: newConsumables,
    });
  };

  // Render a single monster's HP
  const renderMonsterHp = (
    item: InitiativeItem,
    index: number,
    monsterKey: string,
    monsterLabel: string,
    maxHp: number
  ) => {
    const currentHp = props.state.hp[itemHashKey(item)]?.[monsterKey] || 0;
    // Add status class based on health percentage
    const healthPercent = maxHp > 0 ? (currentHp / maxHp) * 100 : 0;
    let statusClass = "";
    if (currentHp <= 0) {
      statusClass = "dnd-ui-monster-status-dead";
    } else if (healthPercent <= 33) {
      statusClass = "dnd-ui-monster-status-injured";
    } else if (healthPercent >= 90) {
      statusClass = "dnd-ui-monster-status-healthy";
    }

    return (
      <div key={`${index}-${monsterKey}`} className="dnd-ui-initiative-monster">
        <div className="dnd-ui-initiative-monster-header">
          <span className={`dnd-ui-initiative-monster-name ${statusClass}`}>{monsterLabel}</span>
          <span className="dnd-ui-initiative-monster-hp">
            <span className="dnd-ui-initiative-hp-value">{currentHp}</span>
            <span className="dnd-ui-initiative-hp-separator">/</span>
            <span className="dnd-ui-initiative-hp-max">{maxHp}</span>
          </span>
        </div>
        <div className="dnd-ui-initiative-monster-actions">
          <input
            type="number"
            className="dnd-ui-initiative-hp-input"
            placeholder="0"
            onChange={(e) => setInputValue(e.target.value)}
          />
          <button
            className="dnd-ui-initiative-hp-button dnd-ui-initiative-damage"
            onClick={() => {
              handleDamage(props.static.items[index], monsterKey, inputValue);
              setInputValue("1");
            }}
            title="Damage"
          >
            −
          </button>
          <button
            className="dnd-ui-initiative-hp-button dnd-ui-initiative-heal"
            onClick={() => {
              handleDamage(props.static.items[index], monsterKey, inputValue, "heal");
              setInputValue("1");
            }}
            title="Heal"
          >
            +
          </button>
        </div>
      </div>
    );
  };

  // Render HP section based on whether it's a group or single monster
  const renderHpSection = (item: InitiativeItem, index: number) => {
    if (!item.hp) return null;

    const hashKey = itemHashKey(item);

    const itemHp = props.state.hp[hashKey] || {};
    const isGroup = typeof item.hp === "object" && Object.keys(item.hp).length > 1;

    if (isGroup) {
      // It's a group of monsters with individual HP tracking
      return (
        <div className="dnd-ui-initiative-group-hp">
          {Object.entries(item.hp as Record<string, number>).map(([key, maxHp]) =>
            renderMonsterHp(item, index, key, key, maxHp)
          )}
        </div>
      );
    } else {
      // It's a single monster
      const monsterKey = Object.keys(itemHp)[0] || "main";
      const maxHp = getMaxHp(item);
      const currentHp = itemHp[monsterKey] || 0;

      // Status class based on health percentage
      const healthPercent = maxHp > 0 ? (currentHp / maxHp) * 100 : 0;
      let statusClass = "";
      if (currentHp <= 0) {
        statusClass = "dnd-ui-monster-status-dead";
      } else if (healthPercent <= 33) {
        statusClass = "dnd-ui-monster-status-injured";
      }

      // Always render HP with inline controls
      return (
        <div className={`dnd-ui-initiative-hp-inline ${statusClass}`}>
          <div className="dnd-ui-initiative-hp-display">
            <span className="dnd-ui-initiative-hp-value">{currentHp}</span>
            <span className="dnd-ui-initiative-hp-separator">/</span>
            <span className="dnd-ui-initiative-hp-max">{maxHp}</span>
          </div>
          <div className="dnd-ui-initiative-hp-controls">
            <input
              type="number"
              className="dnd-ui-initiative-hp-input"
              placeholder="0"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
            />
            <button
              className="dnd-ui-initiative-hp-button dnd-ui-initiative-damage"
              onClick={() => {
                handleDamage(props.static.items[index], monsterKey, inputValue);
                setInputValue("1");
              }}
              title="Damage"
            >
              −
            </button>
            <button
              className="dnd-ui-initiative-hp-button dnd-ui-initiative-heal"
              onClick={() => {
                handleDamage(props.static.items[index], monsterKey, inputValue, "heal");
                setInputValue("1");
              }}
              title="Heal"
            >
              +
            </button>
          </div>
        </div>
      );
    }
  };

  return (
    <div className="dnd-ui-initiative-tracker">
      <div className="dnd-ui-initiative-tracker-controls">
        <div className="dnd-ui-initiative-round-counter">
          Round: <span className="dnd-ui-initiative-round-value">{props.state.round}</span>
        </div>
        <button
          className="dnd-ui-initiative-control-button dnd-ui-initiative-prev"
          onClick={handlePrev}
          aria-label="Previous combatant"
        >
          ◀ Prev
        </button>
        <button
          className="dnd-ui-initiative-control-button dnd-ui-initiative-next"
          onClick={handleNext}
          aria-label="Next combatant"
        >
          Next ▶
        </button>
        <button
          className="dnd-ui-initiative-control-button dnd-ui-initiative-reset"
          onClick={handleReset}
          aria-label="Reset initiative"
        >
          Reset
        </button>
      </div>

      {/* Consumables Section */}
      {props.static.consumables && props.static.consumables.length > 0 && (
        <MultiConsumableCheckboxes
          consumables={props.static.consumables.map(adaptInitiativeConsumable)}
          states={Object.fromEntries(
            props.static.consumables.map((consumable) => [
              consumable.state_key,
              { value: props.state.consumables?.[consumable.state_key] || 0 },
            ])
          )}
          onStateChange={handleConsumableStateChange}
        />
      )}

      <div className="dnd-ui-initiative-list">
        {sortedItems.length === 0 ? (
          <div className="dnd-ui-initiative-empty-state">No combatants added</div>
        ) : (
          <div className="dnd-ui-initiative-items">
            {sortedItems.map(({ item, index, initiative }) => {
              const isActive = index === props.state.activeIndex;
              const hasHp = item.hp !== undefined;
              const isGroupMonster = hasHp && typeof item.hp === "object" && Object.keys(item.hp).length > 1;

              return (
                <div
                  key={index}
                  className={`dnd-ui-initiative-item ${isActive ? "dnd-ui-initiative-item-active" : ""} ${isGroupMonster ? "dnd-ui-initiative-item-group" : ""}`}
                >
                  <div className="dnd-ui-initiative-item-main">
                    <div className="dnd-ui-initiative-roll">
                      <input
                        type="number"
                        value={initiative || ""}
                        onChange={(e) => handleSetInitiative(props.static.items[index], e.target.value)}
                        className="dnd-ui-initiative-input"
                        placeholder="0"
                      />
                    </div>
                    <div>
                      <div className="dnd-ui-initiative-name">
                        {item.link ? (
                          <a href={item.link} className="dnd-ui-initiative-link">
                            {item.name}
                          </a>
                        ) : (
                          item.name
                        )}
                      </div>
                      <div className="dnd-ui-initiative-ac">
                        AC: <span className="dnd-ui-initiative-ac-value">{item.ac}</span>
                      </div>
                    </div>

                    {hasHp && !isGroupMonster && renderHpSection(item, index)}
                  </div>

                  {/* HP actions are now always inline - no separate section needed */}

                  {isGroupMonster && (
                    <>
                      <div className="dnd-ui-divider"></div>
                      <div className="dnd-ui-initiative-group-container">{renderHpSection(item, index)}</div>
                    </>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
