// lib/components/SpellComponents.vue
<script setup lang="ts">
import type { SpellComponentsBlock } from "../types";

const props = defineProps<{
  data: SpellComponentsBlock;
}>();
</script>

<template>
  <div class="dnd-ui-spell-components">
    <div v-if="props.data.casting_time" class="dnd-ui-spell-component-item">
      <span class="dnd-ui-spell-component-label">Casting Time</span>
      <span class="dnd-ui-spell-component-value">{{ props.data.casting_time }}</span>
    </div>
    <div v-if="props.data.range" class="dnd-ui-spell-component-item">
      <span class="dnd-ui-spell-component-label">Range</span>
      <span class="dnd-ui-spell-component-value">{{ props.data.range }}</span>
    </div>
    <div v-if="props.data.components" class="dnd-ui-spell-component-item">
      <span class="dnd-ui-spell-component-label">Components</span>
      <span class="dnd-ui-spell-component-value">{{ props.data.components }}</span>
    </div>
    <div v-if="props.data.duration" class="dnd-ui-spell-component-item">
      <span class="dnd-ui-spell-component-label">Duration</span>
      <span class="dnd-ui-spell-component-value">{{ props.data.duration }}</span>
    </div>
  </div>
</template>

// lib/components/spell-components.tsx
import { SpellComponentsBlock } from "../types";

export function SpellComponents({ data }: { data: SpellComponentsBlock }) {
  const { casting_time, range, components, duration } = data;

  return (
    <div className="dnd-ui-spell-components">
      {casting_time && (
        <div className="dnd-ui-spell-component-item">
          <span className="dnd-ui-spell-component-label">Casting Time</span>
          <span className="dnd-ui-spell-component-value">{casting_time}</span>
        </div>
      )}
      {range && (
        <div className="dnd-ui-spell-component-item">
          <span className="dnd-ui-spell-component-label">Range</span>
          <span className="dnd-ui-spell-component-value">{range}</span>
        </div>
      )}
      {components && (
        <div className="dnd-ui-spell-component-item">
          <span className="dnd-ui-spell-component-label">Components</span>
          <span className="dnd-ui-spell-component-value">{components}</span>
        </div>
      )}
      {duration && (
        <div className="dnd-ui-spell-component-item">
          <span className="dnd-ui-spell-component-label">Duration</span>
          <span className="dnd-ui-spell-component-value">{duration}</span>
        </div>
      )}
    </div>
  );
}
